;;; init.el --- The main entry point of the configuration -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; This file is the main entry point for the Emacs configuration.
;; It sets up the core environment, optimizes startup performance,
;; and loads various configuration modules in a structured manner.
;;
;;; Code:

;;----------------------------------------------------------------------------
;; Core Setup
;;----------------------------------------------------------------------------

;; Optimize Garbage Collection for Startup
(setq gc-cons-threshold most-positive-fixnum)

;; Optimize `auto-mode-alist`
(setq auto-mode-case-fold nil)

;; Add our `lisp' directory to the `load-path'. This must be done first,
;; so Emacs knows where to find our custom modules.
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lisp/lang" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lisp/writing" user-emacs-directory))

;; A clever optimization for startup performance.
;; `file-name-handler-alist' can be slow as it's consulted for every file
;; load. We disable it during startup and restore it once everything is loaded.
(let ((old-file-name-handler-alist file-name-handler-alist))
  (setq file-name-handler-alist nil)
  (add-hook 'emacs-startup-hook
            (lambda ()
              (setq file-name-handler-alist old-file-name-handler-alist))
            ;; Use a priority of 101 to ensure it runs after other startup tasks.
            101))

;;----------------------------------------------------------------------------
;; Module Loading
;;----------------------------------------------------------------------------

;; -- Foundational Modules --
(require 'init-package)
(require 'init-perf)        ; Transient hooks for lazy loading
(require 'init-base)        ; Basic editor settings (encoding, backups, etc.).
(require 'init-ui)          ; Theme, fonts, modeline, and other visuals.
(require 'init-kbd)         ; Keybindings.

;; -- Core Editing Experience --
(require 'init-edit)        ; Editing enhancements (paredit, highlighting, etc.).
(require 'init-completion)  ; The completion framework (e.g., Vertico).
(require 'init-history)     ; Persistence (savehist, recentf, saveplace).
(require 'init-highlight)
(require 'init-snippet)
(require 'init-spell)

;; -- Tools and UI enhancements --
(require 'init-vcs)         ; Version control (Magit).
(require 'init-ibuffer)
(require 'init-project)
(require 'init-dashboard)   ; Startup dashboard.
(require 'init-dired)       ; File manager enhancements.
(require 'init-shell)       ; Eshell configuration.
(require 'init-window)      ; Window management commands.
(require 'init-utils)
(require 'init-workspace)

;; -- Programming  --
(require 'init-prog)      ; General programming settings
(require 'init-lsp)       ; Language Server Protocol (LSP) support.
(require 'init-check)     ; Syntax checking (Flycheck).
(require 'init-dape)      ; Debug Adapter Protocol (DAP) support.
(require 'init-c)         ; C/C++ specific settings
(require 'init-python)

;; writing
(require 'init-org)
(require 'init-markdown)
(require 'init-tex)

;; AI Integration
(require 'init-ai)

;; Misc
(require 'init-reader)
(require 'init-calendar)

;; Load custom settings generated by the Customize interface.
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(and (file-readable-p custom-file) (load custom-file))

;;; init.el ends here
